sudo: false
language: ruby
rvm:
- 2.2.0
script:
- RAILS_ENV=test bundle exec rake --trace db:create db:migrate test
deploy:
  api_key:
    secure: TlA5hVmXl3iaYE2W0yVIMya6Fp6XHlVapueDtRo3ifs9w2MLMfvmQtYEui+Ltleytz8ge/IAfQe6ZYB80yPOom/a5B5+yRiB1mPdsflMflIKNy/N2hzSJoLnxolDy/8oSkfJ5GQHY/PTPn8/Oz43cQBRN+AETDwAqLkpN55/2Xo=
  run: "bin/rake db:migrate"
